server:
  port: 8030
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
  dashboard:
    proxy-stream-allow-list: "*"
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/"
  enpoint:
    hystrix:
      stream:
        enabled: true
